/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculatordemo2;

import javax.swing.JTextArea;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.Field;  // This brings in the Field feature of Java Reflection

class CalculatorUITest {

    private static CalculatorUI classUnderTest;

    @BeforeAll
    public static void setUp() {
        classUnderTest = new CalculatorUI();
    }

    @DisplayName("Testing that writer writes the display")
    @Test
    public void writerSetText() throws Exception {
        // Use reflection to access the private field “text”
        Class cls = classUnderTest.getClass();
        Field field = cls.getDeclaredField("text");
        field.setAccessible(true);
        // Set the value of “text” to “mytext”
        JTextArea text = (JTextArea) field.get(classUnderTest);
        text.setText("mytext");
        // Test that the value of “text” is “mytext”
        assertEquals("mytext", text.getText());
    }

    @DisplayName("Testing reader method")
    @Test
    public void testReader()
    {
        //When the text area is empty
        classUnderTest.text.setText("");
        assertEquals(0.0, classUnderTest.reader());

        //When the text area recieves a number
        classUnderTest.text.setText("75.5");
        assertEquals(75.5, classUnderTest.reader());

        //When the text area recieves a non-number
        classUnderTest.text.setText("wow");
        assertThrows(NumberFormatException.class, classUnderTest::reader);
    }

    @DisplayName("Testing writer method")
    @Test
    public void testWriter()
    {
        //Writing a number value to the text area
        classUnderTest.writer(75.5);
        assertEquals("75.5", classUnderTest.text.getText());

        //Writing a non-number value to the text area
        classUnderTest.writer(Double.NaN);
        assertEquals("", classUnderTest.text.getText());

    }
    
    @Test 
    void appPanelIsCreated() {
        assertNotNull(classUnderTest, "app should have a panel object");
    }
}

